# Generated by Django 6.0.7 on 2026-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_confirmation_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
